<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>openquote-care-sidecar</AssemblyName>
    <RootNamespace>OpenquoteCare.Sidecar</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Openquote" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenquoteCare.Tests" />
  </ItemGroup>

</Project>
