import '@iyulab/desktop-patterns/shell'
import '@iyulab/desktop-patterns/sidebar'
import '@iyulab/desktop-patterns/toolbar'
import '@iyulab/desktop-patterns/page'
import '@iyulab/desktop-compact/button'
import '@iyulab/desktop-compact/input'
import '@iyulab/desktop-compact/select'
import './app.js'
