// Every user-facing string lives here, so a change of UI language touches one file.
export const strings = {
  appName: 'Openquote Care',
  tagline: '분류가 바뀌어도 다시 세지 않는 상담 기록',

  createVault: '새 볼트 만들기',
  openVault: '볼트 열기',
  pickFolder: '폴더 선택',
  pickCreateFolderTitle: '새 볼트를 만들 빈 폴더 선택',
  pickOpenFolderTitle: '열 볼트 폴더 선택',
  folder: '폴더',
  noFolder: '선택한 폴더가 없습니다',
  passphrase: '패스프레이즈',
  passphraseAgain: '패스프레이즈 다시 입력',
  passphraseHint: (min: number) => `${min}자 이상. 볼트를 열 때마다 입력합니다.`,
  create: '만들기',
  open: '열기',
  back: '뒤로',
  working: '처리하고 있습니다…',

  kitTitle: '복구 키트',
  kitLead: '패스프레이즈를 잊으면 이 키로만 기록을 열 수 있습니다. 지금 인쇄하거나 옮겨 적어 보관하세요.',
  kitKey: '볼트 키',
  kitWarnings: [
    '이 키를 가진 사람은 볼트의 모든 기록을 읽을 수 있습니다.',
    '잠금장치가 있는 곳에 보관하세요(상담일지 수기 기록과 같은 기준).',
    '패스프레이즈와 이 키를 모두 잃으면 누구도, 개발사도 기록을 열 수 없습니다.',
  ],
  kitWithoutApp: '앱 없이 여는 방법: 공개 도구 age로 볼트 키를 key.txt에 저장한 뒤 age -d -i key.txt <파일>.age 를 실행합니다.',
  kitPassphraseChange: '패스프레이즈를 바꿔도 이 키는 그대로 유효합니다.',
  print: '인쇄',
  kitConfirmLabel: (n: number) => `보관했는지 확인: 볼트 키의 마지막 묶음(${n}자)을 입력하세요`,
  kitConfirm: '확인',

  unreadable: (n: number) => `읽지 못한 파일 ${n}개 — 다른 기기에서 쓰는 중이거나 손상되었을 수 있습니다.`,
  closeVault: '볼트 닫기',
  cancel: '취소',
  refresh: '다시 읽기',
  toggleSidebar: '사이드바 접기/펼치기',
  navLabel: '탐색',
  navSubjects: '대상자',
  navPractitioners: '담당자',
  navReport: '월 보고',

  report: '월 보고',
  reportForm: '양식',
  reportFormOption: (label: string, version: number) => `${label} (v${version})`,
  year: '연도',
  month: '월',
  monthOption: (m: number) => `${m}월`,
  runReport: '산출',
  noReports: '이 볼트에는 보고 양식이 없습니다.',
  reportPeriod: (from: string, to: string) => `기간 ${from} ~ ${to} · 산출 기록이 볼트에 남았습니다.`,
  reportRow: '분류',
  reportTotal: '계',
  noPractitioner: '(담당자 없음)',
  pending: '재분류 대기',
  pendingHint: '분류 체계가 바뀌어 한 기록이 여러 새 분류로 갈 수 있습니다. 사람이 골라야 칸에 들어갑니다.',
  unmapped: '연계 없음',
  unmappedHint: '연계표에 없는 옛 분류의 기록입니다. 분류 체계 자료를 확인하세요.',
  grandTotal: '전체',
  evidence: (what: string, n: number) => `${what} — 근거 기록 ${n}건`,
  evidenceSubject: '대상자',
  pickCell: '칸의 수를 누르면 그 수를 이룬 기록이 여기에 보입니다.',
  reclassifyTitle: (n: number) => `재분류 대기 ${n}건 — 새 분류를 고르세요`,
  reclassifyLead: '분류 체계가 바뀌며 한 옛 분류가 여러 새 분류로 나뉘었습니다. 앱은 추정하지 않습니다. 기록마다 하나를 고르면 원래 분류는 그대로 남고 새 분류가 덧붙습니다.',
  reclassifyWas: '기존 분류',
  reclassifyTo: '새 분류',
  reclassified: '확정',
  reclassifiedNotice: (n: number) => `재분류 ${n}건을 확정했습니다. 산출을 다시 누르면 표에 반영됩니다.`,
  compareWith: '이전 산출과 비교',
  compare: '비교',
  noEarlierRun: '같은 양식·기간의 이전 산출 기록이 없습니다.',
  runOption: (at: string, version: number, total: number) => `${at.slice(0, 16).replace('T', ' ')} · v${version} · 전체 ${total}`,
  comparisonTitle: (earlierVersion: number, laterVersion: number) => `이전 산출(v${earlierVersion})과 지금 산출(v${laterVersion})의 차이`,
  comparisonCounts: (late: number, removed: number, revised: number, moved: number, unchanged: number) =>
    `늦게 입력 ${late} · 빠짐 ${removed} · 분류 개정 ${revised} · 기록 수정 ${moved} · 그대로 ${unchanged}`,
  changeKind: { late: '늦게 입력', removed: '빠짐', revised: '분류 개정', moved: '기록 수정' },
  changeKindHint: {
    late: '이전 산출 뒤에 입력된 기록입니다.',
    removed: '이전 산출 뒤에 지워졌거나 기간에서 벗어난 기록입니다.',
    revised: '기록은 그대로이고, 분류 체계 개정의 연계표가 새 자리로 옮겼습니다.',
    moved: '기록의 분류나 담당자를 사람이 고쳐 자리가 바뀌었습니다.',
  },
  before: '이전',
  after: '지금',
  nowhere: '—',
  applyPack: '분류 개정 적용',
  applyPackTitle: '적용할 분류 자료(데이터 팩) 폴더 선택',
  packAdded: (items: string[]) => `추가했습니다: ${items.join(', ')}`,
  packNothingNew: '이 자료에는 볼트에 없는 새 분류·양식이 없습니다.',
  definition: {
    scheme: (name: string, version: number) => `분류 ${name} v${version}`,
    crosswalk: (name: string, from: number, to: number) => `연계표 ${name} v${from}→v${to}`,
    report: (name: string, version: number) => `양식 ${name} v${version}`,
  },

  subjects: '대상자',
  noSubjects: '대상자가 없습니다. 이름을 입력해 추가하세요.',
  subjectName: '대상자 이름',
  addSubject: '대상자 추가',
  pickSubject: '대상자를 고르면 회기가 여기에 보입니다.',
  sessions: (name: string) => `${name} — 회기`,
  noSessions: '기록한 회기가 없습니다.',
  newSession: '새 회기',
  sessionDate: '날짜',
  sessionTopic: '주제',
  sessionMethod: '방법',
  sessionPractitioner: '담당자',
  noMethod: '(없음)',
  recordSession: '회기 기록',
  sessionCount: (n: number) => `회기 ${n}건`,
  conflict: '동시 수정',
  conflictTitle: '두 기기에서 서로 모르게 고친 칸',
  conflictLead: '둘 다 보존되어 있습니다. 맞는 값을 고르면 모든 기기에서 그 값으로 정리됩니다.',
  conflictField: { topic: '주제', method: '방법', date: '날짜', practitioner: '담당자' } as Record<string, string>,
  conflictFrom: (device: string) => `기기 ${device}`,
  conflictResolved: '동시 수정을 정리했습니다.',

  practitioners: '담당자',
  noPractitioners: '담당자가 없습니다. 월 보고의 열은 담당자별로 나뉩니다.',
  practitionerName: '담당자 이름',
  addPractitioner: '담당자 추가',
  needPractitioner: '회기를 기록하려면 담당자를 먼저 추가하세요.',

  problems: {
    'passphrase-short': (min: number) => `패스프레이즈는 ${min}자 이상이어야 합니다.`,
    'passphrase-mismatch': '두 패스프레이즈가 다릅니다.',
    'no-folder': '폴더를 먼저 선택하세요.',
    'no-name': '이름을 입력하세요.',
    'no-date': '날짜를 입력하세요.',
    'no-topic': '주제를 고르세요.',
    'no-practitioner': '담당자를 고르세요.',
  },
  errors: {
    'no-vault': '열린 볼트가 없습니다.',
    'kit-not-confirmed': '복구 키트를 먼저 확인하세요.',
    'kit-mismatch': '볼트 키의 마지막 글자와 다릅니다. 다시 확인하세요.',
    'not-a-pack': '이 폴더에는 분류나 보고 양식 자료가 없습니다.',
    'pack-conflict': '볼트에 같은 이름의 다른 분류·양식이 이미 있어 아무것도 적용하지 않았습니다. 자료의 버전을 확인하세요.',
    'already-exists': '이 폴더에는 이미 볼트가 있습니다. 볼트 열기를 쓰세요.',
    'not-a-vault': '이 폴더는 볼트가 아닙니다.',
    'not-encrypted': '암호화되지 않은 볼트는 아직 열 수 없습니다.',
    'wrong-passphrase': '패스프레이즈가 맞지 않습니다.',
    'damaged-key-file': '볼트 키 파일이 손상되었습니다. 복구 키트로 열어야 합니다.',
    'recovery-key': '복구 키가 맞지 않습니다.',
    'invalid-path': '볼트 밖의 경로입니다.',
    'engine-start': '기록 엔진이 시작되지 않았습니다. 앱을 다시 설치해야 할 수 있습니다.',
    engine: '기록 엔진이 요청을 처리하지 못했습니다.',
    io: '파일을 읽거나 쓰지 못했습니다.',
    unknown: '작업을 끝내지 못했습니다.',
  },
  errorDetail: (message: string) => `자세한 내용: ${message}`,
} as const
