// Every user-facing string lives here, so a change of UI language touches one file.
export const strings = {
  appName: 'Openquote Care',
  tagline: '분류가 바뀌어도 다시 세지 않는 상담 기록',

  createVault: '새 볼트 만들기',
  openVault: '볼트 열기',
  pickFolder: '폴더 선택',
  pickCreateFolderTitle: '새 볼트를 만들 빈 폴더 선택',
  pickOpenFolderTitle: '열 볼트 폴더 선택',
  folder: '폴더',
  noFolder: '선택한 폴더가 없습니다',
  passphrase: '패스프레이즈',
  passphraseAgain: '패스프레이즈 다시 입력',
  passphraseHint: (min: number) => `${min}자 이상. 볼트를 열 때마다 입력합니다.`,
  create: '만들기',
  open: '열기',
  back: '뒤로',
  working: '처리하고 있습니다…',

  kitTitle: '복구 키트',
  kitLead: '패스프레이즈를 잊으면 이 키로만 기록을 열 수 있습니다. 지금 인쇄하거나 옮겨 적어 보관하세요.',
  kitKey: '볼트 키',
  kitWarnings: [
    '이 키를 가진 사람은 볼트의 모든 기록을 읽을 수 있습니다.',
    '잠금장치가 있는 곳에 보관하세요(상담일지 수기 기록과 같은 기준).',
    '패스프레이즈와 이 키를 모두 잃으면 누구도, 개발사도 기록을 열 수 없습니다.',
  ],
  kitWithoutApp: '앱 없이 여는 방법: 공개 도구 age로 볼트 키를 key.txt에 저장한 뒤 age -d -i key.txt <파일>.age 를 실행합니다.',
  kitPassphraseChange: '패스프레이즈를 바꿔도 이 키는 그대로 유효합니다.',
  print: '인쇄',
  kitConfirmLabel: (n: number) => `보관했는지 확인: 볼트 키의 마지막 묶음(${n}자)을 입력하세요`,
  kitConfirm: '확인',

  vaultOpen: '볼트가 열렸습니다',
  vaultReady: '기록 화면은 다음 단계에서 이어집니다.',
  unreadable: (n: number) => `읽지 못한 파일 ${n}개 — 다른 기기에서 쓰는 중이거나 손상되었을 수 있습니다.`,
  closeVault: '볼트 닫기',

  problems: {
    'passphrase-short': (min: number) => `패스프레이즈는 ${min}자 이상이어야 합니다.`,
    'passphrase-mismatch': '두 패스프레이즈가 다릅니다.',
    'no-folder': '폴더를 먼저 선택하세요.',
  },
  errors: {
    'no-vault': '열린 볼트가 없습니다.',
    'kit-not-confirmed': '복구 키트를 먼저 확인하세요.',
    'kit-mismatch': '볼트 키의 마지막 글자와 다릅니다. 다시 확인하세요.',
    'already-exists': '이 폴더에는 이미 볼트가 있습니다. 볼트 열기를 쓰세요.',
    'not-a-vault': '이 폴더는 볼트가 아닙니다.',
    'not-encrypted': '암호화되지 않은 볼트는 아직 열 수 없습니다.',
    'wrong-passphrase': '패스프레이즈가 맞지 않습니다.',
    'damaged-key-file': '볼트 키 파일이 손상되었습니다. 복구 키트로 열어야 합니다.',
    'recovery-key': '복구 키가 맞지 않습니다.',
    'invalid-path': '볼트 밖의 경로입니다.',
    'engine-start': '기록 엔진이 시작되지 않았습니다. 앱을 다시 설치해야 할 수 있습니다.',
    engine: '기록 엔진이 요청을 처리하지 못했습니다.',
    io: '파일을 읽거나 쓰지 못했습니다.',
    unknown: '작업을 끝내지 못했습니다.',
  },
  errorDetail: (message: string) => `자세한 내용: ${message}`,
} as const
